### ISSUE TITLE
App crashes in tcp client mode

### ISSUE THREAD

**Issue by phamson02** [mmdagent-ex/MMDAgent-EX#16]
I was following the example in your docs, specifically "[When MMDAgent-EX serves as the client - Communication Using TCP/IP](https://mmdagent-ex.dev/docs/remote-tcpip/#when-mmdagent-ex-serves-as-the-client)," but the app crashes with the error shown in the screenshot below.

![2024-11-01-085928_hyprshot](https://github.com/user-attachments/assets/8bf68d20-3ee2-4ba0-8301-8ea1b440a580)

Further inspection into your source code leads to an attempt that manages to fix the crash in this [PR](#17). It avoids calling `FD_ISSET` with a negative value (`m_server_sd = -1`) when using TCP client mode. However, I'm not entirely sure if this is the best approach, so I'm opening this issue to discuss further.

For additional context, a colleague tested this on macOS without issues, but I am experiencing the crash on Ubuntu 24.10.

**Comment by LeeAkinobu** [comment]
Thanks you for your contribution to MMDAgent-EX!  I confirmed the problem and merged your PR.
